import {
  type EmailTemplate,
  BRAND,
  emailLayout,
  heading,
  paragraph,
  button,
  detailsTable,
  keyValue,
  signature,
  smallText,
} from "./_layout.js";

// ──────────────────────────────────────────────
//  Report Emails
// ──────────────────────────────────────────────

export const dailyReport = (
  reportDate: string,
  reportType: string,
  downloadLink: string,
): EmailTemplate => ({
  subject: `${BRAND.name} — Daily Report for ${reportDate}`,
  html: emailLayout(
    `${heading("Daily Report")}
    ${paragraph("Your daily report has been generated and is ready for download.")}
    ${detailsTable(keyValue("Date", reportDate) + keyValue("Report Type", reportType))}
    ${button("Download Report", downloadLink)}
    ${smallText("This report was automatically generated by the OMG Teams platform.")}
    ${signature()}`,
    `Daily report for ${reportDate} is ready.`,
  ),
  text: `Daily Report for ${reportDate} (${reportType}) is ready. Download: ${downloadLink}`,
});

export const monthlyReport = (
  reportMonth: string,
  reportType: string,
  downloadLink: string,
): EmailTemplate => ({
  subject: `${BRAND.name} — Monthly Report for ${reportMonth}`,
  html: emailLayout(
    `${heading("Monthly Report")}
    ${paragraph("Your monthly report has been generated and is ready for download.")}
    ${detailsTable(keyValue("Month", reportMonth) + keyValue("Report Type", reportType))}
    ${button("Download Report", downloadLink)}
    ${smallText("This report was automatically generated by the OMG Teams platform.")}
    ${signature()}`,
    `Monthly report for ${reportMonth} is ready.`,
  ),
  text: `Monthly Report for ${reportMonth} (${reportType}) is ready. Download: ${downloadLink}`,
});

export const scheduledReportDelivery = (
  reportName: string,
  reportType: string,
  generatedAt: string,
  downloadLink: string,
  recipientEmail: string,
): EmailTemplate => ({
  subject: `${BRAND.name} — Scheduled Report: ${reportName}`,
  html: emailLayout(
    `${heading("Scheduled Report Ready")}
    ${paragraph(`Your scheduled report <strong>${reportName}</strong> has been generated successfully.`)}
    ${detailsTable(
      keyValue("Report Name", reportName) +
        keyValue("Report Type", reportType) +
        keyValue("Generated At", generatedAt),
    )}
    ${button("Download Report", downloadLink)}
    ${smallText(`This report was automatically generated and delivered to ${recipientEmail}.`)}
    ${signature()}`,
    `Scheduled report "${reportName}" is ready for download.`,
  ),
  text: `Scheduled Report "${reportName}" (${reportType}) generated at ${generatedAt}. Download: ${downloadLink}`,
});
