// ──────────────────────────────────────────────
//  Indian districts — every state and union territory
//
//  ~775 districts total. Each row links to its parent state via
//  `parentValue`, which the seed/backfill helper resolves to the
//  state's row id at insert time.
//
//  Collision handling: where the same district name exists in two
//  states (Aurangabad MH/BR, Bilaspur HP/CG, Hamirpur HP/UP,
//  Pratapgarh UP/RJ, Balrampur UP/CG, Bijapur KA/CG), the value is
//  suffixed with the state code. The displayed `label` stays clean
//  so recruiters see normal names in the dropdown.
//
//  Renamed districts use the current official name in `label` with
//  the historical name in parentheses (e.g. "Bengaluru (Bangalore)")
//  so existing seed values stay backward-compatible.
// ──────────────────────────────────────────────

import type { LocationSeed } from "./dropdown-data.js";

export const LOCATIONS: LocationSeed[] = [
  // ── Andaman & Nicobar Islands (3) ──
  { value: "nicobar",                 label: "Nicobar",                  parentValue: "andaman_nicobar" },
  { value: "north_middle_andaman",    label: "North and Middle Andaman", parentValue: "andaman_nicobar" },
  { value: "south_andaman",           label: "South Andaman",            parentValue: "andaman_nicobar" },

  // ── Andhra Pradesh (26) ──
  { value: "alluri_sitharama_raju",   label: "Alluri Sitharama Raju",    parentValue: "andhra_pradesh" },
  { value: "anakapalli",              label: "Anakapalli",               parentValue: "andhra_pradesh" },
  { value: "anantapur",               label: "Anantapur",                parentValue: "andhra_pradesh" },
  { value: "annamayya",               label: "Annamayya",                parentValue: "andhra_pradesh" },
  { value: "bapatla",                 label: "Bapatla",                  parentValue: "andhra_pradesh" },
  { value: "chittoor",                label: "Chittoor",                 parentValue: "andhra_pradesh" },
  { value: "east_godavari",           label: "East Godavari",            parentValue: "andhra_pradesh" },
  { value: "eluru",                   label: "Eluru",                    parentValue: "andhra_pradesh" },
  { value: "guntur",                  label: "Guntur",                   parentValue: "andhra_pradesh" },
  { value: "kakinada",                label: "Kakinada",                 parentValue: "andhra_pradesh" },
  { value: "konaseema",               label: "Konaseema",                parentValue: "andhra_pradesh" },
  { value: "krishna",                 label: "Krishna",                  parentValue: "andhra_pradesh" },
  { value: "kurnool",                 label: "Kurnool",                  parentValue: "andhra_pradesh" },
  { value: "nandyal",                 label: "Nandyal",                  parentValue: "andhra_pradesh" },
  { value: "nellore",                 label: "Nellore",                  parentValue: "andhra_pradesh" },
  { value: "ntr",                     label: "NTR",                      parentValue: "andhra_pradesh" },
  { value: "palnadu",                 label: "Palnadu",                  parentValue: "andhra_pradesh" },
  { value: "parvathipuram_manyam",    label: "Parvathipuram Manyam",     parentValue: "andhra_pradesh" },
  { value: "prakasam",                label: "Prakasam",                 parentValue: "andhra_pradesh" },
  { value: "sri_sathya_sai",          label: "Sri Sathya Sai",           parentValue: "andhra_pradesh" },
  { value: "srikakulam",              label: "Srikakulam",               parentValue: "andhra_pradesh" },
  { value: "tirupati",                label: "Tirupati",                 parentValue: "andhra_pradesh" },
  { value: "visakhapatnam",           label: "Visakhapatnam",            parentValue: "andhra_pradesh" },
  { value: "vizianagaram",            label: "Vizianagaram",             parentValue: "andhra_pradesh" },
  { value: "west_godavari",           label: "West Godavari",            parentValue: "andhra_pradesh" },
  { value: "ysr_kadapa",              label: "YSR Kadapa",               parentValue: "andhra_pradesh" },

  // ── Arunachal Pradesh (26) ──
  { value: "anjaw",                   label: "Anjaw",                    parentValue: "arunachal_pradesh" },
  { value: "changlang",               label: "Changlang",                parentValue: "arunachal_pradesh" },
  { value: "dibang_valley",           label: "Dibang Valley",            parentValue: "arunachal_pradesh" },
  { value: "east_kameng",             label: "East Kameng",              parentValue: "arunachal_pradesh" },
  { value: "east_siang",              label: "East Siang",               parentValue: "arunachal_pradesh" },
  { value: "itanagar",                label: "Itanagar Capital Complex", parentValue: "arunachal_pradesh" },
  { value: "kamle",                   label: "Kamle",                    parentValue: "arunachal_pradesh" },
  { value: "kra_daadi",               label: "Kra Daadi",                parentValue: "arunachal_pradesh" },
  { value: "kurung_kumey",            label: "Kurung Kumey",             parentValue: "arunachal_pradesh" },
  { value: "lepa_rada",               label: "Lepa Rada",                parentValue: "arunachal_pradesh" },
  { value: "lohit",                   label: "Lohit",                    parentValue: "arunachal_pradesh" },
  { value: "longding",                label: "Longding",                 parentValue: "arunachal_pradesh" },
  { value: "lower_dibang_valley",     label: "Lower Dibang Valley",      parentValue: "arunachal_pradesh" },
  { value: "lower_siang",             label: "Lower Siang",              parentValue: "arunachal_pradesh" },
  { value: "lower_subansiri",         label: "Lower Subansiri",          parentValue: "arunachal_pradesh" },
  { value: "namsai",                  label: "Namsai",                   parentValue: "arunachal_pradesh" },
  { value: "pakke_kessang",           label: "Pakke Kessang",            parentValue: "arunachal_pradesh" },
  { value: "papum_pare",              label: "Papum Pare",               parentValue: "arunachal_pradesh" },
  { value: "shi_yomi",                label: "Shi Yomi",                 parentValue: "arunachal_pradesh" },
  { value: "siang",                   label: "Siang",                    parentValue: "arunachal_pradesh" },
  { value: "tawang",                  label: "Tawang",                   parentValue: "arunachal_pradesh" },
  { value: "tirap",                   label: "Tirap",                    parentValue: "arunachal_pradesh" },
  { value: "upper_siang",             label: "Upper Siang",              parentValue: "arunachal_pradesh" },
  { value: "upper_subansiri",         label: "Upper Subansiri",          parentValue: "arunachal_pradesh" },
  { value: "west_kameng",             label: "West Kameng",              parentValue: "arunachal_pradesh" },
  { value: "west_siang",              label: "West Siang",               parentValue: "arunachal_pradesh" },

  // ── Assam (35) ──
  { value: "bajali",                  label: "Bajali",                   parentValue: "assam" },
  { value: "baksa",                   label: "Baksa",                    parentValue: "assam" },
  { value: "barpeta",                 label: "Barpeta",                  parentValue: "assam" },
  { value: "biswanath",               label: "Biswanath",                parentValue: "assam" },
  { value: "bongaigaon",              label: "Bongaigaon",               parentValue: "assam" },
  { value: "cachar",                  label: "Cachar",                   parentValue: "assam" },
  { value: "charaideo",               label: "Charaideo",                parentValue: "assam" },
  { value: "chirang",                 label: "Chirang",                  parentValue: "assam" },
  { value: "darrang",                 label: "Darrang",                  parentValue: "assam" },
  { value: "dhemaji",                 label: "Dhemaji",                  parentValue: "assam" },
  { value: "dhubri",                  label: "Dhubri",                   parentValue: "assam" },
  { value: "dibrugarh",               label: "Dibrugarh",                parentValue: "assam" },
  { value: "dima_hasao",              label: "Dima Hasao",               parentValue: "assam" },
  { value: "goalpara",                label: "Goalpara",                 parentValue: "assam" },
  { value: "golaghat",                label: "Golaghat",                 parentValue: "assam" },
  { value: "hailakandi",              label: "Hailakandi",               parentValue: "assam" },
  { value: "hojai",                   label: "Hojai",                    parentValue: "assam" },
  { value: "jorhat",                  label: "Jorhat",                   parentValue: "assam" },
  { value: "kamrup",                  label: "Kamrup",                   parentValue: "assam" },
  { value: "kamrup_metropolitan",     label: "Kamrup Metropolitan",      parentValue: "assam" },
  { value: "karbi_anglong",           label: "Karbi Anglong",            parentValue: "assam" },
  { value: "karimganj",               label: "Karimganj",                parentValue: "assam" },
  { value: "kokrajhar",               label: "Kokrajhar",                parentValue: "assam" },
  { value: "lakhimpur",               label: "Lakhimpur",                parentValue: "assam" },
  { value: "majuli",                  label: "Majuli",                   parentValue: "assam" },
  { value: "morigaon",                label: "Morigaon",                 parentValue: "assam" },
  { value: "nagaon",                  label: "Nagaon",                   parentValue: "assam" },
  { value: "nalbari",                 label: "Nalbari",                  parentValue: "assam" },
  { value: "sivasagar",               label: "Sivasagar",                parentValue: "assam" },
  { value: "sonitpur",                label: "Sonitpur",                 parentValue: "assam" },
  { value: "south_salmara_mankachar", label: "South Salmara-Mankachar",  parentValue: "assam" },
  { value: "tamulpur",                label: "Tamulpur",                 parentValue: "assam" },
  { value: "tinsukia",                label: "Tinsukia",                 parentValue: "assam" },
  { value: "udalguri",                label: "Udalguri",                 parentValue: "assam" },
  { value: "west_karbi_anglong",      label: "West Karbi Anglong",       parentValue: "assam" },

  // ── Bihar (38) ──
  { value: "araria",                  label: "Araria",                   parentValue: "bihar" },
  { value: "arwal",                   label: "Arwal",                    parentValue: "bihar" },
  { value: "aurangabad_br",           label: "Aurangabad",               parentValue: "bihar" },
  { value: "banka",                   label: "Banka",                    parentValue: "bihar" },
  { value: "begusarai",               label: "Begusarai",                parentValue: "bihar" },
  { value: "bhagalpur",               label: "Bhagalpur",                parentValue: "bihar" },
  { value: "bhojpur",                 label: "Bhojpur",                  parentValue: "bihar" },
  { value: "buxar",                   label: "Buxar",                    parentValue: "bihar" },
  { value: "darbhanga",               label: "Darbhanga",                parentValue: "bihar" },
  { value: "east_champaran",          label: "East Champaran",           parentValue: "bihar" },
  { value: "gaya",                    label: "Gaya",                     parentValue: "bihar" },
  { value: "gopalganj",               label: "Gopalganj",                parentValue: "bihar" },
  { value: "jamui",                   label: "Jamui",                    parentValue: "bihar" },
  { value: "jehanabad",               label: "Jehanabad",                parentValue: "bihar" },
  { value: "kaimur",                  label: "Kaimur",                   parentValue: "bihar" },
  { value: "katihar",                 label: "Katihar",                  parentValue: "bihar" },
  { value: "khagaria",                label: "Khagaria",                 parentValue: "bihar" },
  { value: "kishanganj",              label: "Kishanganj",               parentValue: "bihar" },
  { value: "lakhisarai",              label: "Lakhisarai",               parentValue: "bihar" },
  { value: "madhepura",               label: "Madhepura",                parentValue: "bihar" },
  { value: "madhubani",               label: "Madhubani",                parentValue: "bihar" },
  { value: "munger",                  label: "Munger",                   parentValue: "bihar" },
  { value: "muzaffarpur",             label: "Muzaffarpur",              parentValue: "bihar" },
  { value: "nalanda",                 label: "Nalanda",                  parentValue: "bihar" },
  { value: "nawada",                  label: "Nawada",                   parentValue: "bihar" },
  { value: "patna",                   label: "Patna",                    parentValue: "bihar" },
  { value: "purnia",                  label: "Purnia",                   parentValue: "bihar" },
  { value: "rohtas",                  label: "Rohtas",                   parentValue: "bihar" },
  { value: "saharsa",                 label: "Saharsa",                  parentValue: "bihar" },
  { value: "samastipur",              label: "Samastipur",               parentValue: "bihar" },
  { value: "saran",                   label: "Saran",                    parentValue: "bihar" },
  { value: "sheikhpura",              label: "Sheikhpura",               parentValue: "bihar" },
  { value: "sheohar",                 label: "Sheohar",                  parentValue: "bihar" },
  { value: "sitamarhi",               label: "Sitamarhi",                parentValue: "bihar" },
  { value: "siwan",                   label: "Siwan",                    parentValue: "bihar" },
  { value: "supaul",                  label: "Supaul",                   parentValue: "bihar" },
  { value: "vaishali",                label: "Vaishali",                 parentValue: "bihar" },
  { value: "west_champaran",          label: "West Champaran",           parentValue: "bihar" },

  // ── Chandigarh (1) ──
  { value: "chandigarh",              label: "Chandigarh",               parentValue: "chandigarh" },

  // ── Chhattisgarh (33) ──
  { value: "balod",                   label: "Balod",                    parentValue: "chhattisgarh" },
  { value: "baloda_bazar",            label: "Baloda Bazar",             parentValue: "chhattisgarh" },
  { value: "balrampur_cg",            label: "Balrampur-Ramanujganj",    parentValue: "chhattisgarh" },
  { value: "bastar",                  label: "Bastar",                   parentValue: "chhattisgarh" },
  { value: "bemetara",                label: "Bemetara",                 parentValue: "chhattisgarh" },
  { value: "bijapur_cg",              label: "Bijapur",                  parentValue: "chhattisgarh" },
  { value: "bilaspur_cg",             label: "Bilaspur",                 parentValue: "chhattisgarh" },
  { value: "dantewada",               label: "Dantewada",                parentValue: "chhattisgarh" },
  { value: "dhamtari",                label: "Dhamtari",                 parentValue: "chhattisgarh" },
  { value: "durg",                    label: "Durg",                     parentValue: "chhattisgarh" },
  { value: "gariaband",               label: "Gariaband",                parentValue: "chhattisgarh" },
  { value: "gaurela_pendra_marwahi",  label: "Gaurela-Pendra-Marwahi",   parentValue: "chhattisgarh" },
  { value: "janjgir_champa",          label: "Janjgir-Champa",           parentValue: "chhattisgarh" },
  { value: "jashpur",                 label: "Jashpur",                  parentValue: "chhattisgarh" },
  { value: "kabirdham",               label: "Kabirdham (Kawardha)",     parentValue: "chhattisgarh" },
  { value: "kanker",                  label: "Kanker",                   parentValue: "chhattisgarh" },
  { value: "khairagarh",              label: "Khairagarh-Chhuikhadan-Gandai", parentValue: "chhattisgarh" },
  { value: "kondagaon",               label: "Kondagaon",                parentValue: "chhattisgarh" },
  { value: "korba",                   label: "Korba",                    parentValue: "chhattisgarh" },
  { value: "korea",                   label: "Korea",                    parentValue: "chhattisgarh" },
  { value: "mahasamund",              label: "Mahasamund",               parentValue: "chhattisgarh" },
  { value: "manendragarh",            label: "Manendragarh-Chirmiri-Bharatpur", parentValue: "chhattisgarh" },
  { value: "mohla_manpur",            label: "Mohla-Manpur-Ambagarh Chowki", parentValue: "chhattisgarh" },
  { value: "mungeli",                 label: "Mungeli",                  parentValue: "chhattisgarh" },
  { value: "narayanpur",              label: "Narayanpur",               parentValue: "chhattisgarh" },
  { value: "raigarh",                 label: "Raigarh",                  parentValue: "chhattisgarh" },
  { value: "raipur",                  label: "Raipur",                   parentValue: "chhattisgarh" },
  { value: "rajnandgaon",             label: "Rajnandgaon",              parentValue: "chhattisgarh" },
  { value: "sakti",                   label: "Sakti",                    parentValue: "chhattisgarh" },
  { value: "sarangarh_bilaigarh",     label: "Sarangarh-Bilaigarh",      parentValue: "chhattisgarh" },
  { value: "sukma",                   label: "Sukma",                    parentValue: "chhattisgarh" },
  { value: "surajpur",                label: "Surajpur",                 parentValue: "chhattisgarh" },
  { value: "surguja",                 label: "Surguja",                  parentValue: "chhattisgarh" },

  // ── Dadra & Nagar Haveli and Daman & Diu (3) ──
  { value: "dadra_nagar_haveli_dist", label: "Dadra and Nagar Haveli",   parentValue: "dadra_nagar_haveli" },
  { value: "daman",                   label: "Daman",                    parentValue: "dadra_nagar_haveli" },
  { value: "diu",                     label: "Diu",                      parentValue: "dadra_nagar_haveli" },

  // ── Delhi (11) ──
  { value: "central_delhi",           label: "Central Delhi",            parentValue: "delhi" },
  { value: "east_delhi",              label: "East Delhi",               parentValue: "delhi" },
  { value: "new_delhi",               label: "New Delhi",                parentValue: "delhi" },
  { value: "north_delhi",             label: "North Delhi",              parentValue: "delhi" },
  { value: "north_east_delhi",        label: "North East Delhi",         parentValue: "delhi" },
  { value: "north_west_delhi",        label: "North West Delhi",         parentValue: "delhi" },
  { value: "shahdara",                label: "Shahdara",                 parentValue: "delhi" },
  { value: "south_delhi",             label: "South Delhi",              parentValue: "delhi" },
  { value: "south_east_delhi",        label: "South East Delhi",         parentValue: "delhi" },
  { value: "south_west_delhi",        label: "South West Delhi",         parentValue: "delhi" },
  { value: "west_delhi",              label: "West Delhi",               parentValue: "delhi" },

  // ── Goa (2) ──
  { value: "north_goa",               label: "North Goa",                parentValue: "goa" },
  { value: "south_goa",               label: "South Goa",                parentValue: "goa" },

  // ── Gujarat (33) ──
  { value: "ahmedabad",               label: "Ahmedabad",                parentValue: "gujarat" },
  { value: "amreli",                  label: "Amreli",                   parentValue: "gujarat" },
  { value: "anand",                   label: "Anand",                    parentValue: "gujarat" },
  { value: "aravalli",                label: "Aravalli",                 parentValue: "gujarat" },
  { value: "banaskantha",             label: "Banaskantha",              parentValue: "gujarat" },
  { value: "bharuch",                 label: "Bharuch",                  parentValue: "gujarat" },
  { value: "bhavnagar",               label: "Bhavnagar",                parentValue: "gujarat" },
  { value: "botad",                   label: "Botad",                    parentValue: "gujarat" },
  { value: "chhota_udaipur",          label: "Chhota Udaipur",           parentValue: "gujarat" },
  { value: "dahod",                   label: "Dahod",                    parentValue: "gujarat" },
  { value: "dang",                    label: "Dang",                     parentValue: "gujarat" },
  { value: "devbhoomi_dwarka",        label: "Devbhoomi Dwarka",         parentValue: "gujarat" },
  { value: "gandhinagar",             label: "Gandhinagar",              parentValue: "gujarat" },
  { value: "gir_somnath",             label: "Gir Somnath",              parentValue: "gujarat" },
  { value: "jamnagar",                label: "Jamnagar",                 parentValue: "gujarat" },
  { value: "junagadh",                label: "Junagadh",                 parentValue: "gujarat" },
  { value: "kheda",                   label: "Kheda",                    parentValue: "gujarat" },
  { value: "kutch",                   label: "Kutch",                    parentValue: "gujarat" },
  { value: "mahisagar",               label: "Mahisagar",                parentValue: "gujarat" },
  { value: "mehsana",                 label: "Mehsana",                  parentValue: "gujarat" },
  { value: "morbi",                   label: "Morbi",                    parentValue: "gujarat" },
  { value: "narmada",                 label: "Narmada",                  parentValue: "gujarat" },
  { value: "navsari",                 label: "Navsari",                  parentValue: "gujarat" },
  { value: "panchmahal",              label: "Panchmahal",               parentValue: "gujarat" },
  { value: "patan",                   label: "Patan",                    parentValue: "gujarat" },
  { value: "porbandar",               label: "Porbandar",                parentValue: "gujarat" },
  { value: "rajkot",                  label: "Rajkot",                   parentValue: "gujarat" },
  { value: "sabarkantha",             label: "Sabarkantha",              parentValue: "gujarat" },
  { value: "surat",                   label: "Surat",                    parentValue: "gujarat" },
  { value: "surendranagar",           label: "Surendranagar",            parentValue: "gujarat" },
  { value: "tapi",                    label: "Tapi",                     parentValue: "gujarat" },
  { value: "vadodara",                label: "Vadodara",                 parentValue: "gujarat" },
  { value: "valsad",                  label: "Valsad",                   parentValue: "gujarat" },

  // ── Haryana (22) ──
  { value: "ambala",                  label: "Ambala",                   parentValue: "haryana" },
  { value: "bhiwani",                 label: "Bhiwani",                  parentValue: "haryana" },
  { value: "charkhi_dadri",           label: "Charkhi Dadri",            parentValue: "haryana" },
  { value: "faridabad",               label: "Faridabad",                parentValue: "haryana" },
  { value: "fatehabad",               label: "Fatehabad",                parentValue: "haryana" },
  { value: "gurugram",                label: "Gurugram",                 parentValue: "haryana" },
  { value: "hisar",                   label: "Hisar",                    parentValue: "haryana" },
  { value: "jhajjar",                 label: "Jhajjar",                  parentValue: "haryana" },
  { value: "jind",                    label: "Jind",                     parentValue: "haryana" },
  { value: "kaithal",                 label: "Kaithal",                  parentValue: "haryana" },
  { value: "karnal",                  label: "Karnal",                   parentValue: "haryana" },
  { value: "kurukshetra",             label: "Kurukshetra",              parentValue: "haryana" },
  { value: "mahendragarh",            label: "Mahendragarh",             parentValue: "haryana" },
  { value: "nuh",                     label: "Nuh",                      parentValue: "haryana" },
  { value: "palwal",                  label: "Palwal",                   parentValue: "haryana" },
  { value: "panchkula",               label: "Panchkula",                parentValue: "haryana" },
  { value: "panipat",                 label: "Panipat",                  parentValue: "haryana" },
  { value: "rewari",                  label: "Rewari",                   parentValue: "haryana" },
  { value: "rohtak",                  label: "Rohtak",                   parentValue: "haryana" },
  { value: "sirsa",                   label: "Sirsa",                    parentValue: "haryana" },
  { value: "sonipat",                 label: "Sonipat",                  parentValue: "haryana" },
  { value: "yamunanagar",             label: "Yamunanagar",              parentValue: "haryana" },

  // ── Himachal Pradesh (12) ──
  { value: "bilaspur_hp",             label: "Bilaspur",                 parentValue: "himachal_pradesh" },
  { value: "chamba",                  label: "Chamba",                   parentValue: "himachal_pradesh" },
  { value: "hamirpur_hp",             label: "Hamirpur",                 parentValue: "himachal_pradesh" },
  { value: "kangra",                  label: "Kangra",                   parentValue: "himachal_pradesh" },
  { value: "kinnaur",                 label: "Kinnaur",                  parentValue: "himachal_pradesh" },
  { value: "kullu",                   label: "Kullu",                    parentValue: "himachal_pradesh" },
  { value: "lahaul_spiti",            label: "Lahaul and Spiti",         parentValue: "himachal_pradesh" },
  { value: "mandi",                   label: "Mandi",                    parentValue: "himachal_pradesh" },
  { value: "shimla",                  label: "Shimla",                   parentValue: "himachal_pradesh" },
  { value: "sirmaur",                 label: "Sirmaur",                  parentValue: "himachal_pradesh" },
  { value: "solan",                   label: "Solan",                    parentValue: "himachal_pradesh" },
  { value: "una",                     label: "Una",                      parentValue: "himachal_pradesh" },

  // ── Jammu & Kashmir (20) ──
  { value: "anantnag",                label: "Anantnag",                 parentValue: "jammu_kashmir" },
  { value: "bandipora",               label: "Bandipora",                parentValue: "jammu_kashmir" },
  { value: "baramulla",               label: "Baramulla",                parentValue: "jammu_kashmir" },
  { value: "budgam",                  label: "Budgam",                   parentValue: "jammu_kashmir" },
  { value: "doda",                    label: "Doda",                     parentValue: "jammu_kashmir" },
  { value: "ganderbal",               label: "Ganderbal",                parentValue: "jammu_kashmir" },
  { value: "jammu",                   label: "Jammu",                    parentValue: "jammu_kashmir" },
  { value: "kathua",                  label: "Kathua",                   parentValue: "jammu_kashmir" },
  { value: "kishtwar",                label: "Kishtwar",                 parentValue: "jammu_kashmir" },
  { value: "kulgam",                  label: "Kulgam",                   parentValue: "jammu_kashmir" },
  { value: "kupwara",                 label: "Kupwara",                  parentValue: "jammu_kashmir" },
  { value: "poonch",                  label: "Poonch",                   parentValue: "jammu_kashmir" },
  { value: "pulwama",                 label: "Pulwama",                  parentValue: "jammu_kashmir" },
  { value: "rajouri",                 label: "Rajouri",                  parentValue: "jammu_kashmir" },
  { value: "ramban",                  label: "Ramban",                   parentValue: "jammu_kashmir" },
  { value: "reasi",                   label: "Reasi",                    parentValue: "jammu_kashmir" },
  { value: "samba",                   label: "Samba",                    parentValue: "jammu_kashmir" },
  { value: "shopian",                 label: "Shopian",                  parentValue: "jammu_kashmir" },
  { value: "srinagar",                label: "Srinagar",                 parentValue: "jammu_kashmir" },
  { value: "udhampur",                label: "Udhampur",                 parentValue: "jammu_kashmir" },

  // ── Jharkhand (24) ──
  { value: "bokaro",                  label: "Bokaro",                   parentValue: "jharkhand" },
  { value: "chatra",                  label: "Chatra",                   parentValue: "jharkhand" },
  { value: "deoghar",                 label: "Deoghar",                  parentValue: "jharkhand" },
  { value: "dhanbad",                 label: "Dhanbad",                  parentValue: "jharkhand" },
  { value: "dumka",                   label: "Dumka",                    parentValue: "jharkhand" },
  { value: "east_singhbhum",          label: "East Singhbhum",           parentValue: "jharkhand" },
  { value: "garhwa",                  label: "Garhwa",                   parentValue: "jharkhand" },
  { value: "giridih",                 label: "Giridih",                  parentValue: "jharkhand" },
  { value: "godda",                   label: "Godda",                    parentValue: "jharkhand" },
  { value: "gumla",                   label: "Gumla",                    parentValue: "jharkhand" },
  { value: "hazaribagh",              label: "Hazaribagh",               parentValue: "jharkhand" },
  { value: "jamtara",                 label: "Jamtara",                  parentValue: "jharkhand" },
  { value: "khunti",                  label: "Khunti",                   parentValue: "jharkhand" },
  { value: "koderma",                 label: "Koderma",                  parentValue: "jharkhand" },
  { value: "latehar",                 label: "Latehar",                  parentValue: "jharkhand" },
  { value: "lohardaga",               label: "Lohardaga",                parentValue: "jharkhand" },
  { value: "pakur",                   label: "Pakur",                    parentValue: "jharkhand" },
  { value: "palamu",                  label: "Palamu",                   parentValue: "jharkhand" },
  { value: "ramgarh",                 label: "Ramgarh",                  parentValue: "jharkhand" },
  { value: "ranchi",                  label: "Ranchi",                   parentValue: "jharkhand" },
  { value: "sahebganj",               label: "Sahebganj",                parentValue: "jharkhand" },
  { value: "seraikela_kharsawan",     label: "Seraikela Kharsawan",      parentValue: "jharkhand" },
  { value: "simdega",                 label: "Simdega",                  parentValue: "jharkhand" },
  { value: "west_singhbhum",          label: "West Singhbhum",           parentValue: "jharkhand" },

  // ── Karnataka (31) ──
  { value: "bagalkot",                label: "Bagalkot",                 parentValue: "karnataka" },
  { value: "ballari",                 label: "Ballari (Bellary)",        parentValue: "karnataka" },
  { value: "belagavi",                label: "Belagavi (Belgaum)",       parentValue: "karnataka" },
  { value: "bengaluru_rural",         label: "Bengaluru Rural",          parentValue: "karnataka" },
  { value: "bengaluru_urban",         label: "Bengaluru Urban",          parentValue: "karnataka" },
  { value: "bidar",                   label: "Bidar",                    parentValue: "karnataka" },
  { value: "chamarajanagar",          label: "Chamarajanagar",           parentValue: "karnataka" },
  { value: "chikballapur",            label: "Chikballapur",             parentValue: "karnataka" },
  { value: "chikkamagaluru",          label: "Chikkamagaluru",           parentValue: "karnataka" },
  { value: "chitradurga",             label: "Chitradurga",              parentValue: "karnataka" },
  { value: "dakshina_kannada",        label: "Dakshina Kannada",         parentValue: "karnataka" },
  { value: "davanagere",              label: "Davanagere",               parentValue: "karnataka" },
  { value: "dharwad",                 label: "Dharwad",                  parentValue: "karnataka" },
  { value: "gadag",                   label: "Gadag",                    parentValue: "karnataka" },
  { value: "hassan",                  label: "Hassan",                   parentValue: "karnataka" },
  { value: "haveri",                  label: "Haveri",                   parentValue: "karnataka" },
  { value: "kalaburagi",              label: "Kalaburagi (Gulbarga)",    parentValue: "karnataka" },
  { value: "kodagu",                  label: "Kodagu",                   parentValue: "karnataka" },
  { value: "kolar",                   label: "Kolar",                    parentValue: "karnataka" },
  { value: "koppal",                  label: "Koppal",                   parentValue: "karnataka" },
  { value: "mandya",                  label: "Mandya",                   parentValue: "karnataka" },
  { value: "mysuru",                  label: "Mysuru (Mysore)",          parentValue: "karnataka" },
  { value: "raichur",                 label: "Raichur",                  parentValue: "karnataka" },
  { value: "ramanagara",              label: "Ramanagara",               parentValue: "karnataka" },
  { value: "shivamogga",              label: "Shivamogga (Shimoga)",     parentValue: "karnataka" },
  { value: "tumakuru",                label: "Tumakuru (Tumkur)",        parentValue: "karnataka" },
  { value: "udupi",                   label: "Udupi",                    parentValue: "karnataka" },
  { value: "uttara_kannada",          label: "Uttara Kannada",           parentValue: "karnataka" },
  { value: "vijayanagara",            label: "Vijayanagara",             parentValue: "karnataka" },
  { value: "vijayapura",              label: "Vijayapura (Bijapur)",     parentValue: "karnataka" },
  { value: "yadgir",                  label: "Yadgir",                   parentValue: "karnataka" },

  // ── Kerala (14) ──
  { value: "alappuzha",               label: "Alappuzha",                parentValue: "kerala" },
  { value: "ernakulam",               label: "Ernakulam",                parentValue: "kerala" },
  { value: "idukki",                  label: "Idukki",                   parentValue: "kerala" },
  { value: "kannur",                  label: "Kannur",                   parentValue: "kerala" },
  { value: "kasaragod",               label: "Kasaragod",                parentValue: "kerala" },
  { value: "kollam",                  label: "Kollam",                   parentValue: "kerala" },
  { value: "kottayam",                label: "Kottayam",                 parentValue: "kerala" },
  { value: "kozhikode",               label: "Kozhikode",                parentValue: "kerala" },
  { value: "malappuram",              label: "Malappuram",               parentValue: "kerala" },
  { value: "palakkad",                label: "Palakkad",                 parentValue: "kerala" },
  { value: "pathanamthitta",          label: "Pathanamthitta",           parentValue: "kerala" },
  { value: "thiruvananthapuram",      label: "Thiruvananthapuram",       parentValue: "kerala" },
  { value: "thrissur",                label: "Thrissur",                 parentValue: "kerala" },
  { value: "wayanad",                 label: "Wayanad",                  parentValue: "kerala" },

  // ── Ladakh (2) ──
  { value: "kargil",                  label: "Kargil",                   parentValue: "ladakh" },
  { value: "leh",                     label: "Leh",                      parentValue: "ladakh" },

  // ── Lakshadweep (1) ──
  { value: "lakshadweep",             label: "Lakshadweep",              parentValue: "lakshadweep" },

  // ── Madhya Pradesh (55) ──
  { value: "agar_malwa",              label: "Agar Malwa",               parentValue: "madhya_pradesh" },
  { value: "alirajpur",               label: "Alirajpur",                parentValue: "madhya_pradesh" },
  { value: "anuppur",                 label: "Anuppur",                  parentValue: "madhya_pradesh" },
  { value: "ashoknagar",              label: "Ashoknagar",               parentValue: "madhya_pradesh" },
  { value: "balaghat",                label: "Balaghat",                 parentValue: "madhya_pradesh" },
  { value: "barwani",                 label: "Barwani",                  parentValue: "madhya_pradesh" },
  { value: "betul",                   label: "Betul",                    parentValue: "madhya_pradesh" },
  { value: "bhind",                   label: "Bhind",                    parentValue: "madhya_pradesh" },
  { value: "bhopal",                  label: "Bhopal",                   parentValue: "madhya_pradesh" },
  { value: "burhanpur",               label: "Burhanpur",                parentValue: "madhya_pradesh" },
  { value: "chhatarpur",              label: "Chhatarpur",               parentValue: "madhya_pradesh" },
  { value: "chhindwara",              label: "Chhindwara",               parentValue: "madhya_pradesh" },
  { value: "damoh",                   label: "Damoh",                    parentValue: "madhya_pradesh" },
  { value: "datia",                   label: "Datia",                    parentValue: "madhya_pradesh" },
  { value: "dewas",                   label: "Dewas",                    parentValue: "madhya_pradesh" },
  { value: "dhar",                    label: "Dhar",                     parentValue: "madhya_pradesh" },
  { value: "dindori",                 label: "Dindori",                  parentValue: "madhya_pradesh" },
  { value: "guna",                    label: "Guna",                     parentValue: "madhya_pradesh" },
  { value: "gwalior",                 label: "Gwalior",                  parentValue: "madhya_pradesh" },
  { value: "harda",                   label: "Harda",                    parentValue: "madhya_pradesh" },
  { value: "indore",                  label: "Indore",                   parentValue: "madhya_pradesh" },
  { value: "jabalpur",                label: "Jabalpur",                 parentValue: "madhya_pradesh" },
  { value: "jhabua",                  label: "Jhabua",                   parentValue: "madhya_pradesh" },
  { value: "katni",                   label: "Katni",                    parentValue: "madhya_pradesh" },
  { value: "khandwa",                 label: "Khandwa",                  parentValue: "madhya_pradesh" },
  { value: "khargone",                label: "Khargone",                 parentValue: "madhya_pradesh" },
  { value: "maihar",                  label: "Maihar",                   parentValue: "madhya_pradesh" },
  { value: "mandla",                  label: "Mandla",                   parentValue: "madhya_pradesh" },
  { value: "mandsaur",                label: "Mandsaur",                 parentValue: "madhya_pradesh" },
  { value: "mauganj",                 label: "Mauganj",                  parentValue: "madhya_pradesh" },
  { value: "morena",                  label: "Morena",                   parentValue: "madhya_pradesh" },
  { value: "narmadapuram",            label: "Narmadapuram (Hoshangabad)", parentValue: "madhya_pradesh" },
  { value: "narsinghpur",             label: "Narsinghpur",              parentValue: "madhya_pradesh" },
  { value: "neemuch",                 label: "Neemuch",                  parentValue: "madhya_pradesh" },
  { value: "niwari",                  label: "Niwari",                   parentValue: "madhya_pradesh" },
  { value: "pandhurna",               label: "Pandhurna",                parentValue: "madhya_pradesh" },
  { value: "panna",                   label: "Panna",                    parentValue: "madhya_pradesh" },
  { value: "raisen",                  label: "Raisen",                   parentValue: "madhya_pradesh" },
  { value: "rajgarh",                 label: "Rajgarh",                  parentValue: "madhya_pradesh" },
  { value: "ratlam",                  label: "Ratlam",                   parentValue: "madhya_pradesh" },
  { value: "rewa",                    label: "Rewa",                     parentValue: "madhya_pradesh" },
  { value: "sagar",                   label: "Sagar",                    parentValue: "madhya_pradesh" },
  { value: "satna",                   label: "Satna",                    parentValue: "madhya_pradesh" },
  { value: "sehore",                  label: "Sehore",                   parentValue: "madhya_pradesh" },
  { value: "seoni",                   label: "Seoni",                    parentValue: "madhya_pradesh" },
  { value: "shahdol",                 label: "Shahdol",                  parentValue: "madhya_pradesh" },
  { value: "shajapur",                label: "Shajapur",                 parentValue: "madhya_pradesh" },
  { value: "sheopur",                 label: "Sheopur",                  parentValue: "madhya_pradesh" },
  { value: "shivpuri",                label: "Shivpuri",                 parentValue: "madhya_pradesh" },
  { value: "sidhi",                   label: "Sidhi",                    parentValue: "madhya_pradesh" },
  { value: "singrauli",               label: "Singrauli",                parentValue: "madhya_pradesh" },
  { value: "tikamgarh",               label: "Tikamgarh",                parentValue: "madhya_pradesh" },
  { value: "ujjain",                  label: "Ujjain",                   parentValue: "madhya_pradesh" },
  { value: "umaria",                  label: "Umaria",                   parentValue: "madhya_pradesh" },
  { value: "vidisha",                 label: "Vidisha",                  parentValue: "madhya_pradesh" },

  // ── Maharashtra (36) ──
  { value: "ahmednagar",              label: "Ahmednagar",               parentValue: "maharashtra" },
  { value: "akola",                   label: "Akola",                    parentValue: "maharashtra" },
  { value: "amravati",                label: "Amravati",                 parentValue: "maharashtra" },
  { value: "aurangabad_mh",           label: "Chhatrapati Sambhajinagar (Aurangabad)", parentValue: "maharashtra" },
  { value: "beed",                    label: "Beed",                     parentValue: "maharashtra" },
  { value: "bhandara",                label: "Bhandara",                 parentValue: "maharashtra" },
  { value: "buldhana",                label: "Buldhana",                 parentValue: "maharashtra" },
  { value: "chandrapur",              label: "Chandrapur",               parentValue: "maharashtra" },
  { value: "dharashiv",               label: "Dharashiv (Osmanabad)",    parentValue: "maharashtra" },
  { value: "dhule",                   label: "Dhule",                    parentValue: "maharashtra" },
  { value: "gadchiroli",              label: "Gadchiroli",               parentValue: "maharashtra" },
  { value: "gondia",                  label: "Gondia",                   parentValue: "maharashtra" },
  { value: "hingoli",                 label: "Hingoli",                  parentValue: "maharashtra" },
  { value: "jalgaon",                 label: "Jalgaon",                  parentValue: "maharashtra" },
  { value: "jalna",                   label: "Jalna",                    parentValue: "maharashtra" },
  { value: "kolhapur",                label: "Kolhapur",                 parentValue: "maharashtra" },
  { value: "latur",                   label: "Latur",                    parentValue: "maharashtra" },
  { value: "mumbai",                  label: "Mumbai City",              parentValue: "maharashtra" },
  { value: "mumbai_suburban",         label: "Mumbai Suburban",          parentValue: "maharashtra" },
  { value: "nagpur",                  label: "Nagpur",                   parentValue: "maharashtra" },
  { value: "nanded",                  label: "Nanded",                   parentValue: "maharashtra" },
  { value: "nandurbar",               label: "Nandurbar",                parentValue: "maharashtra" },
  { value: "nashik",                  label: "Nashik",                   parentValue: "maharashtra" },
  { value: "palghar",                 label: "Palghar",                  parentValue: "maharashtra" },
  { value: "parbhani",                label: "Parbhani",                 parentValue: "maharashtra" },
  { value: "pune",                    label: "Pune",                     parentValue: "maharashtra" },
  { value: "raigad",                  label: "Raigad",                   parentValue: "maharashtra" },
  { value: "ratnagiri",               label: "Ratnagiri",                parentValue: "maharashtra" },
  { value: "sangli",                  label: "Sangli",                   parentValue: "maharashtra" },
  { value: "satara",                  label: "Satara",                   parentValue: "maharashtra" },
  { value: "sindhudurg",              label: "Sindhudurg",               parentValue: "maharashtra" },
  { value: "solapur",                 label: "Solapur",                  parentValue: "maharashtra" },
  { value: "thane",                   label: "Thane",                    parentValue: "maharashtra" },
  { value: "wardha",                  label: "Wardha",                   parentValue: "maharashtra" },
  { value: "washim",                  label: "Washim",                   parentValue: "maharashtra" },
  { value: "yavatmal",                label: "Yavatmal",                 parentValue: "maharashtra" },

  // ── Manipur (16) ──
  { value: "bishnupur",               label: "Bishnupur",                parentValue: "manipur" },
  { value: "chandel",                 label: "Chandel",                  parentValue: "manipur" },
  { value: "churachandpur",           label: "Churachandpur",            parentValue: "manipur" },
  { value: "imphal_east",             label: "Imphal East",              parentValue: "manipur" },
  { value: "imphal_west",             label: "Imphal West",              parentValue: "manipur" },
  { value: "jiribam",                 label: "Jiribam",                  parentValue: "manipur" },
  { value: "kakching",                label: "Kakching",                 parentValue: "manipur" },
  { value: "kamjong",                 label: "Kamjong",                  parentValue: "manipur" },
  { value: "kangpokpi",               label: "Kangpokpi",                parentValue: "manipur" },
  { value: "noney",                   label: "Noney",                    parentValue: "manipur" },
  { value: "pherzawl",                label: "Pherzawl",                 parentValue: "manipur" },
  { value: "senapati",                label: "Senapati",                 parentValue: "manipur" },
  { value: "tamenglong",              label: "Tamenglong",               parentValue: "manipur" },
  { value: "tengnoupal",              label: "Tengnoupal",               parentValue: "manipur" },
  { value: "thoubal",                 label: "Thoubal",                  parentValue: "manipur" },
  { value: "ukhrul",                  label: "Ukhrul",                   parentValue: "manipur" },

  // ── Meghalaya (12) ──
  { value: "east_garo_hills",         label: "East Garo Hills",          parentValue: "meghalaya" },
  { value: "east_jaintia_hills",      label: "East Jaintia Hills",       parentValue: "meghalaya" },
  { value: "east_khasi_hills",        label: "East Khasi Hills",         parentValue: "meghalaya" },
  { value: "eastern_west_khasi_hills",label: "Eastern West Khasi Hills", parentValue: "meghalaya" },
  { value: "north_garo_hills",        label: "North Garo Hills",         parentValue: "meghalaya" },
  { value: "ri_bhoi",                 label: "Ri Bhoi",                  parentValue: "meghalaya" },
  { value: "south_garo_hills",        label: "South Garo Hills",         parentValue: "meghalaya" },
  { value: "south_west_garo_hills",   label: "South West Garo Hills",    parentValue: "meghalaya" },
  { value: "south_west_khasi_hills",  label: "South West Khasi Hills",   parentValue: "meghalaya" },
  { value: "west_garo_hills",         label: "West Garo Hills",          parentValue: "meghalaya" },
  { value: "west_jaintia_hills",      label: "West Jaintia Hills",       parentValue: "meghalaya" },
  { value: "west_khasi_hills",        label: "West Khasi Hills",         parentValue: "meghalaya" },

  // ── Mizoram (11) ──
  { value: "aizawl",                  label: "Aizawl",                   parentValue: "mizoram" },
  { value: "champhai",                label: "Champhai",                 parentValue: "mizoram" },
  { value: "hnahthial",               label: "Hnahthial",                parentValue: "mizoram" },
  { value: "khawzawl",                label: "Khawzawl",                 parentValue: "mizoram" },
  { value: "kolasib",                 label: "Kolasib",                  parentValue: "mizoram" },
  { value: "lawngtlai",               label: "Lawngtlai",                parentValue: "mizoram" },
  { value: "lunglei",                 label: "Lunglei",                  parentValue: "mizoram" },
  { value: "mamit",                   label: "Mamit",                    parentValue: "mizoram" },
  { value: "saiha",                   label: "Saiha",                    parentValue: "mizoram" },
  { value: "saitual",                 label: "Saitual",                  parentValue: "mizoram" },
  { value: "serchhip",                label: "Serchhip",                 parentValue: "mizoram" },

  // ── Nagaland (16) ──
  { value: "chumukedima",             label: "Chumukedima",              parentValue: "nagaland" },
  { value: "dimapur",                 label: "Dimapur",                  parentValue: "nagaland" },
  { value: "kiphire",                 label: "Kiphire",                  parentValue: "nagaland" },
  { value: "kohima",                  label: "Kohima",                   parentValue: "nagaland" },
  { value: "longleng",                label: "Longleng",                 parentValue: "nagaland" },
  { value: "mokokchung",              label: "Mokokchung",               parentValue: "nagaland" },
  { value: "mon",                     label: "Mon",                      parentValue: "nagaland" },
  { value: "niuland",                 label: "Niuland",                  parentValue: "nagaland" },
  { value: "noklak",                  label: "Noklak",                   parentValue: "nagaland" },
  { value: "peren",                   label: "Peren",                    parentValue: "nagaland" },
  { value: "phek",                    label: "Phek",                     parentValue: "nagaland" },
  { value: "shamator",                label: "Shamator",                 parentValue: "nagaland" },
  { value: "tseminyu",                label: "Tseminyu",                 parentValue: "nagaland" },
  { value: "tuensang",                label: "Tuensang",                 parentValue: "nagaland" },
  { value: "wokha",                   label: "Wokha",                    parentValue: "nagaland" },
  { value: "zunheboto",               label: "Zunheboto",                parentValue: "nagaland" },

  // ── Odisha (30) ──
  { value: "angul",                   label: "Angul",                    parentValue: "odisha" },
  { value: "balangir",                label: "Balangir",                 parentValue: "odisha" },
  { value: "balasore",                label: "Balasore",                 parentValue: "odisha" },
  { value: "bargarh",                 label: "Bargarh",                  parentValue: "odisha" },
  { value: "bhadrak",                 label: "Bhadrak",                  parentValue: "odisha" },
  { value: "boudh",                   label: "Boudh",                    parentValue: "odisha" },
  { value: "cuttack",                 label: "Cuttack",                  parentValue: "odisha" },
  { value: "deogarh",                 label: "Deogarh",                  parentValue: "odisha" },
  { value: "dhenkanal",               label: "Dhenkanal",                parentValue: "odisha" },
  { value: "gajapati",                label: "Gajapati",                 parentValue: "odisha" },
  { value: "ganjam",                  label: "Ganjam",                   parentValue: "odisha" },
  { value: "jagatsinghpur",           label: "Jagatsinghpur",            parentValue: "odisha" },
  { value: "jajpur",                  label: "Jajpur",                   parentValue: "odisha" },
  { value: "jharsuguda",              label: "Jharsuguda",               parentValue: "odisha" },
  { value: "kalahandi",               label: "Kalahandi",                parentValue: "odisha" },
  { value: "kandhamal",               label: "Kandhamal",                parentValue: "odisha" },
  { value: "kendrapara",              label: "Kendrapara",               parentValue: "odisha" },
  { value: "kendujhar",               label: "Kendujhar",                parentValue: "odisha" },
  { value: "khordha",                 label: "Khordha",                  parentValue: "odisha" },
  { value: "koraput",                 label: "Koraput",                  parentValue: "odisha" },
  { value: "malkangiri",              label: "Malkangiri",               parentValue: "odisha" },
  { value: "mayurbhanj",              label: "Mayurbhanj",               parentValue: "odisha" },
  { value: "nabarangpur",             label: "Nabarangpur",              parentValue: "odisha" },
  { value: "nayagarh",                label: "Nayagarh",                 parentValue: "odisha" },
  { value: "nuapada",                 label: "Nuapada",                  parentValue: "odisha" },
  { value: "puri",                    label: "Puri",                     parentValue: "odisha" },
  { value: "rayagada",                label: "Rayagada",                 parentValue: "odisha" },
  { value: "sambalpur",               label: "Sambalpur",                parentValue: "odisha" },
  { value: "subarnapur",              label: "Subarnapur",               parentValue: "odisha" },
  { value: "sundargarh",              label: "Sundargarh",               parentValue: "odisha" },

  // ── Puducherry (4) ──
  { value: "karaikal",                label: "Karaikal",                 parentValue: "puducherry" },
  { value: "mahe",                    label: "Mahe",                     parentValue: "puducherry" },
  { value: "puducherry",              label: "Puducherry",               parentValue: "puducherry" },
  { value: "yanam",                   label: "Yanam",                    parentValue: "puducherry" },

  // ── Punjab (23) ──
  { value: "amritsar",                label: "Amritsar",                 parentValue: "punjab" },
  { value: "barnala",                 label: "Barnala",                  parentValue: "punjab" },
  { value: "bathinda",                label: "Bathinda",                 parentValue: "punjab" },
  { value: "faridkot",                label: "Faridkot",                 parentValue: "punjab" },
  { value: "fatehgarh_sahib",         label: "Fatehgarh Sahib",          parentValue: "punjab" },
  { value: "fazilka",                 label: "Fazilka",                  parentValue: "punjab" },
  { value: "ferozepur",               label: "Ferozepur",                parentValue: "punjab" },
  { value: "gurdaspur",               label: "Gurdaspur",                parentValue: "punjab" },
  { value: "hoshiarpur",              label: "Hoshiarpur",               parentValue: "punjab" },
  { value: "jalandhar",               label: "Jalandhar",                parentValue: "punjab" },
  { value: "kapurthala",              label: "Kapurthala",               parentValue: "punjab" },
  { value: "ludhiana",                label: "Ludhiana",                 parentValue: "punjab" },
  { value: "malerkotla",              label: "Malerkotla",               parentValue: "punjab" },
  { value: "mansa",                   label: "Mansa",                    parentValue: "punjab" },
  { value: "moga",                    label: "Moga",                     parentValue: "punjab" },
  { value: "mohali",                  label: "Mohali (SAS Nagar)",       parentValue: "punjab" },
  { value: "muktsar",                 label: "Sri Muktsar Sahib",        parentValue: "punjab" },
  { value: "nawanshahr",              label: "Shaheed Bhagat Singh Nagar", parentValue: "punjab" },
  { value: "pathankot",               label: "Pathankot",                parentValue: "punjab" },
  { value: "patiala",                 label: "Patiala",                  parentValue: "punjab" },
  { value: "rupnagar",                label: "Rupnagar",                 parentValue: "punjab" },
  { value: "sangrur",                 label: "Sangrur",                  parentValue: "punjab" },
  { value: "tarn_taran",              label: "Tarn Taran",               parentValue: "punjab" },

  // ── Rajasthan (33) ──
  { value: "ajmer",                   label: "Ajmer",                    parentValue: "rajasthan" },
  { value: "alwar",                   label: "Alwar",                    parentValue: "rajasthan" },
  { value: "banswara",                label: "Banswara",                 parentValue: "rajasthan" },
  { value: "baran",                   label: "Baran",                    parentValue: "rajasthan" },
  { value: "barmer",                  label: "Barmer",                   parentValue: "rajasthan" },
  { value: "bharatpur",               label: "Bharatpur",                parentValue: "rajasthan" },
  { value: "bhilwara",                label: "Bhilwara",                 parentValue: "rajasthan" },
  { value: "bikaner",                 label: "Bikaner",                  parentValue: "rajasthan" },
  { value: "bundi",                   label: "Bundi",                    parentValue: "rajasthan" },
  { value: "chittorgarh",             label: "Chittorgarh",              parentValue: "rajasthan" },
  { value: "churu",                   label: "Churu",                    parentValue: "rajasthan" },
  { value: "dausa",                   label: "Dausa",                    parentValue: "rajasthan" },
  { value: "dholpur",                 label: "Dholpur",                  parentValue: "rajasthan" },
  { value: "dungarpur",               label: "Dungarpur",                parentValue: "rajasthan" },
  { value: "hanumangarh",             label: "Hanumangarh",              parentValue: "rajasthan" },
  { value: "jaipur",                  label: "Jaipur",                   parentValue: "rajasthan" },
  { value: "jaisalmer",               label: "Jaisalmer",                parentValue: "rajasthan" },
  { value: "jalore",                  label: "Jalore",                   parentValue: "rajasthan" },
  { value: "jhalawar",                label: "Jhalawar",                 parentValue: "rajasthan" },
  { value: "jhunjhunu",               label: "Jhunjhunu",                parentValue: "rajasthan" },
  { value: "jodhpur",                 label: "Jodhpur",                  parentValue: "rajasthan" },
  { value: "karauli",                 label: "Karauli",                  parentValue: "rajasthan" },
  { value: "kota",                    label: "Kota",                     parentValue: "rajasthan" },
  { value: "nagaur",                  label: "Nagaur",                   parentValue: "rajasthan" },
  { value: "pali",                    label: "Pali",                     parentValue: "rajasthan" },
  { value: "pratapgarh_rj",           label: "Pratapgarh",               parentValue: "rajasthan" },
  { value: "rajsamand",               label: "Rajsamand",                parentValue: "rajasthan" },
  { value: "sawai_madhopur",          label: "Sawai Madhopur",           parentValue: "rajasthan" },
  { value: "sikar",                   label: "Sikar",                    parentValue: "rajasthan" },
  { value: "sirohi",                  label: "Sirohi",                   parentValue: "rajasthan" },
  { value: "sri_ganganagar",          label: "Sri Ganganagar",           parentValue: "rajasthan" },
  { value: "tonk",                    label: "Tonk",                     parentValue: "rajasthan" },
  { value: "udaipur",                 label: "Udaipur",                  parentValue: "rajasthan" },

  // ── Sikkim (6) ──
  { value: "gangtok",                 label: "Gangtok (East Sikkim)",    parentValue: "sikkim" },
  { value: "gyalshing",               label: "Gyalshing (West Sikkim)",  parentValue: "sikkim" },
  { value: "mangan",                  label: "Mangan (North Sikkim)",    parentValue: "sikkim" },
  { value: "namchi",                  label: "Namchi (South Sikkim)",    parentValue: "sikkim" },
  { value: "pakyong",                 label: "Pakyong",                  parentValue: "sikkim" },
  { value: "soreng",                  label: "Soreng",                   parentValue: "sikkim" },

  // ── Tamil Nadu (38) ──
  { value: "ariyalur",                label: "Ariyalur",                 parentValue: "tamil_nadu" },
  { value: "chengalpattu",            label: "Chengalpattu",             parentValue: "tamil_nadu" },
  { value: "chennai",                 label: "Chennai",                  parentValue: "tamil_nadu" },
  { value: "coimbatore",              label: "Coimbatore",               parentValue: "tamil_nadu" },
  { value: "cuddalore",               label: "Cuddalore",                parentValue: "tamil_nadu" },
  { value: "dharmapuri",              label: "Dharmapuri",               parentValue: "tamil_nadu" },
  { value: "dindigul",                label: "Dindigul",                 parentValue: "tamil_nadu" },
  { value: "erode",                   label: "Erode",                    parentValue: "tamil_nadu" },
  { value: "kallakurichi",            label: "Kallakurichi",             parentValue: "tamil_nadu" },
  { value: "kancheepuram",            label: "Kancheepuram",             parentValue: "tamil_nadu" },
  { value: "kanyakumari",             label: "Kanyakumari",              parentValue: "tamil_nadu" },
  { value: "karur",                   label: "Karur",                    parentValue: "tamil_nadu" },
  { value: "krishnagiri",             label: "Krishnagiri",              parentValue: "tamil_nadu" },
  { value: "madurai",                 label: "Madurai",                  parentValue: "tamil_nadu" },
  { value: "mayiladuthurai",          label: "Mayiladuthurai",           parentValue: "tamil_nadu" },
  { value: "nagapattinam",            label: "Nagapattinam",             parentValue: "tamil_nadu" },
  { value: "namakkal",                label: "Namakkal",                 parentValue: "tamil_nadu" },
  { value: "nilgiris",                label: "Nilgiris",                 parentValue: "tamil_nadu" },
  { value: "perambalur",              label: "Perambalur",               parentValue: "tamil_nadu" },
  { value: "pudukkottai",             label: "Pudukkottai",              parentValue: "tamil_nadu" },
  { value: "ramanathapuram",          label: "Ramanathapuram",           parentValue: "tamil_nadu" },
  { value: "ranipet",                 label: "Ranipet",                  parentValue: "tamil_nadu" },
  { value: "salem",                   label: "Salem",                    parentValue: "tamil_nadu" },
  { value: "sivaganga",               label: "Sivaganga",                parentValue: "tamil_nadu" },
  { value: "tenkasi",                 label: "Tenkasi",                  parentValue: "tamil_nadu" },
  { value: "thanjavur",               label: "Thanjavur",                parentValue: "tamil_nadu" },
  { value: "theni",                   label: "Theni",                    parentValue: "tamil_nadu" },
  { value: "thoothukudi",             label: "Thoothukudi",              parentValue: "tamil_nadu" },
  { value: "tiruchirappalli",         label: "Tiruchirappalli",          parentValue: "tamil_nadu" },
  { value: "tirunelveli",             label: "Tirunelveli",              parentValue: "tamil_nadu" },
  { value: "tirupattur",              label: "Tirupattur",               parentValue: "tamil_nadu" },
  { value: "tiruppur",                label: "Tiruppur",                 parentValue: "tamil_nadu" },
  { value: "tiruvallur",              label: "Tiruvallur",               parentValue: "tamil_nadu" },
  { value: "tiruvannamalai",          label: "Tiruvannamalai",           parentValue: "tamil_nadu" },
  { value: "tiruvarur",               label: "Tiruvarur",                parentValue: "tamil_nadu" },
  { value: "vellore",                 label: "Vellore",                  parentValue: "tamil_nadu" },
  { value: "viluppuram",              label: "Viluppuram",               parentValue: "tamil_nadu" },
  { value: "virudhunagar",            label: "Virudhunagar",             parentValue: "tamil_nadu" },

  // ── Telangana (33) ──
  { value: "adilabad",                label: "Adilabad",                 parentValue: "telangana" },
  { value: "bhadradri_kothagudem",    label: "Bhadradri Kothagudem",     parentValue: "telangana" },
  { value: "hanamkonda",              label: "Hanamkonda",               parentValue: "telangana" },
  { value: "hyderabad",               label: "Hyderabad",                parentValue: "telangana" },
  { value: "jagtial",                 label: "Jagtial",                  parentValue: "telangana" },
  { value: "jangaon",                 label: "Jangaon",                  parentValue: "telangana" },
  { value: "jayashankar_bhupalpally", label: "Jayashankar Bhupalpally",  parentValue: "telangana" },
  { value: "jogulamba_gadwal",        label: "Jogulamba Gadwal",         parentValue: "telangana" },
  { value: "kamareddy",               label: "Kamareddy",                parentValue: "telangana" },
  { value: "karimnagar",              label: "Karimnagar",               parentValue: "telangana" },
  { value: "khammam",                 label: "Khammam",                  parentValue: "telangana" },
  { value: "kumuram_bheem_asifabad",  label: "Kumuram Bheem Asifabad",   parentValue: "telangana" },
  { value: "mahabubabad",             label: "Mahabubabad",              parentValue: "telangana" },
  { value: "mahbubnagar",             label: "Mahbubnagar",              parentValue: "telangana" },
  { value: "mancherial",              label: "Mancherial",               parentValue: "telangana" },
  { value: "medak",                   label: "Medak",                    parentValue: "telangana" },
  { value: "medchal_malkajgiri",      label: "Medchal-Malkajgiri",       parentValue: "telangana" },
  { value: "mulugu",                  label: "Mulugu",                   parentValue: "telangana" },
  { value: "nagarkurnool",            label: "Nagarkurnool",             parentValue: "telangana" },
  { value: "nalgonda",                label: "Nalgonda",                 parentValue: "telangana" },
  { value: "narayanpet",              label: "Narayanpet",               parentValue: "telangana" },
  { value: "nirmal",                  label: "Nirmal",                   parentValue: "telangana" },
  { value: "nizamabad",               label: "Nizamabad",                parentValue: "telangana" },
  { value: "peddapalli",              label: "Peddapalli",               parentValue: "telangana" },
  { value: "rajanna_sircilla",        label: "Rajanna Sircilla",         parentValue: "telangana" },
  { value: "ranga_reddy",             label: "Ranga Reddy",              parentValue: "telangana" },
  { value: "sangareddy",              label: "Sangareddy",               parentValue: "telangana" },
  { value: "siddipet",                label: "Siddipet",                 parentValue: "telangana" },
  { value: "suryapet",                label: "Suryapet",                 parentValue: "telangana" },
  { value: "vikarabad",               label: "Vikarabad",                parentValue: "telangana" },
  { value: "wanaparthy",              label: "Wanaparthy",               parentValue: "telangana" },
  { value: "warangal",                label: "Warangal",                 parentValue: "telangana" },
  { value: "yadadri_bhuvanagiri",     label: "Yadadri Bhuvanagiri",      parentValue: "telangana" },

  // ── Tripura (8) ──
  { value: "dhalai",                  label: "Dhalai",                   parentValue: "tripura" },
  { value: "gomati",                  label: "Gomati",                   parentValue: "tripura" },
  { value: "khowai",                  label: "Khowai",                   parentValue: "tripura" },
  { value: "north_tripura",           label: "North Tripura",            parentValue: "tripura" },
  { value: "sepahijala",              label: "Sepahijala",               parentValue: "tripura" },
  { value: "south_tripura",           label: "South Tripura",            parentValue: "tripura" },
  { value: "unakoti",                 label: "Unakoti",                  parentValue: "tripura" },
  { value: "west_tripura",            label: "West Tripura",             parentValue: "tripura" },

  // ── Uttar Pradesh (75) ──
  { value: "agra",                    label: "Agra",                     parentValue: "uttar_pradesh" },
  { value: "aligarh",                 label: "Aligarh",                  parentValue: "uttar_pradesh" },
  { value: "ambedkar_nagar",          label: "Ambedkar Nagar",           parentValue: "uttar_pradesh" },
  { value: "amethi",                  label: "Amethi",                   parentValue: "uttar_pradesh" },
  { value: "amroha",                  label: "Amroha",                   parentValue: "uttar_pradesh" },
  { value: "auraiya",                 label: "Auraiya",                  parentValue: "uttar_pradesh" },
  { value: "ayodhya",                 label: "Ayodhya",                  parentValue: "uttar_pradesh" },
  { value: "azamgarh",                label: "Azamgarh",                 parentValue: "uttar_pradesh" },
  { value: "baghpat",                 label: "Baghpat",                  parentValue: "uttar_pradesh" },
  { value: "bahraich",                label: "Bahraich",                 parentValue: "uttar_pradesh" },
  { value: "ballia",                  label: "Ballia",                   parentValue: "uttar_pradesh" },
  { value: "balrampur_up",            label: "Balrampur",                parentValue: "uttar_pradesh" },
  { value: "banda",                   label: "Banda",                    parentValue: "uttar_pradesh" },
  { value: "barabanki",               label: "Barabanki",                parentValue: "uttar_pradesh" },
  { value: "bareilly",                label: "Bareilly",                 parentValue: "uttar_pradesh" },
  { value: "basti",                   label: "Basti",                    parentValue: "uttar_pradesh" },
  { value: "bhadohi",                 label: "Bhadohi",                  parentValue: "uttar_pradesh" },
  { value: "bijnor",                  label: "Bijnor",                   parentValue: "uttar_pradesh" },
  { value: "budaun",                  label: "Budaun",                   parentValue: "uttar_pradesh" },
  { value: "bulandshahr",             label: "Bulandshahr",              parentValue: "uttar_pradesh" },
  { value: "chandauli",               label: "Chandauli",                parentValue: "uttar_pradesh" },
  { value: "chitrakoot",              label: "Chitrakoot",               parentValue: "uttar_pradesh" },
  { value: "deoria",                  label: "Deoria",                   parentValue: "uttar_pradesh" },
  { value: "etah",                    label: "Etah",                     parentValue: "uttar_pradesh" },
  { value: "etawah",                  label: "Etawah",                   parentValue: "uttar_pradesh" },
  { value: "farrukhabad",             label: "Farrukhabad",              parentValue: "uttar_pradesh" },
  { value: "fatehpur",                label: "Fatehpur",                 parentValue: "uttar_pradesh" },
  { value: "firozabad",               label: "Firozabad",                parentValue: "uttar_pradesh" },
  { value: "gautam_buddha_nagar",     label: "Gautam Buddha Nagar",      parentValue: "uttar_pradesh" },
  { value: "ghaziabad",               label: "Ghaziabad",                parentValue: "uttar_pradesh" },
  { value: "ghazipur",                label: "Ghazipur",                 parentValue: "uttar_pradesh" },
  { value: "gonda",                   label: "Gonda",                    parentValue: "uttar_pradesh" },
  { value: "gorakhpur",               label: "Gorakhpur",                parentValue: "uttar_pradesh" },
  { value: "hamirpur_up",             label: "Hamirpur",                 parentValue: "uttar_pradesh" },
  { value: "hapur",                   label: "Hapur",                    parentValue: "uttar_pradesh" },
  { value: "hardoi",                  label: "Hardoi",                   parentValue: "uttar_pradesh" },
  { value: "hathras",                 label: "Hathras",                  parentValue: "uttar_pradesh" },
  { value: "jalaun",                  label: "Jalaun",                   parentValue: "uttar_pradesh" },
  { value: "jaunpur",                 label: "Jaunpur",                  parentValue: "uttar_pradesh" },
  { value: "jhansi",                  label: "Jhansi",                   parentValue: "uttar_pradesh" },
  { value: "kannauj",                 label: "Kannauj",                  parentValue: "uttar_pradesh" },
  { value: "kanpur_dehat",            label: "Kanpur Dehat",             parentValue: "uttar_pradesh" },
  { value: "kanpur_nagar",            label: "Kanpur Nagar",             parentValue: "uttar_pradesh" },
  { value: "kasganj",                 label: "Kasganj",                  parentValue: "uttar_pradesh" },
  { value: "kaushambi",               label: "Kaushambi",                parentValue: "uttar_pradesh" },
  { value: "kheri",                   label: "Kheri",                    parentValue: "uttar_pradesh" },
  { value: "kushinagar",              label: "Kushinagar",               parentValue: "uttar_pradesh" },
  { value: "lalitpur",                label: "Lalitpur",                 parentValue: "uttar_pradesh" },
  { value: "lucknow",                 label: "Lucknow",                  parentValue: "uttar_pradesh" },
  { value: "maharajganj",             label: "Maharajganj",              parentValue: "uttar_pradesh" },
  { value: "mahoba",                  label: "Mahoba",                   parentValue: "uttar_pradesh" },
  { value: "mainpuri",                label: "Mainpuri",                 parentValue: "uttar_pradesh" },
  { value: "mathura",                 label: "Mathura",                  parentValue: "uttar_pradesh" },
  { value: "mau",                     label: "Mau",                      parentValue: "uttar_pradesh" },
  { value: "meerut",                  label: "Meerut",                   parentValue: "uttar_pradesh" },
  { value: "mirzapur",                label: "Mirzapur",                 parentValue: "uttar_pradesh" },
  { value: "moradabad",               label: "Moradabad",                parentValue: "uttar_pradesh" },
  { value: "muzaffarnagar",           label: "Muzaffarnagar",            parentValue: "uttar_pradesh" },
  { value: "pilibhit",                label: "Pilibhit",                 parentValue: "uttar_pradesh" },
  { value: "pratapgarh_up",           label: "Pratapgarh",               parentValue: "uttar_pradesh" },
  { value: "prayagraj",               label: "Prayagraj",                parentValue: "uttar_pradesh" },
  { value: "raebareli",               label: "Raebareli",                parentValue: "uttar_pradesh" },
  { value: "rampur",                  label: "Rampur",                   parentValue: "uttar_pradesh" },
  { value: "saharanpur",              label: "Saharanpur",               parentValue: "uttar_pradesh" },
  { value: "sambhal",                 label: "Sambhal",                  parentValue: "uttar_pradesh" },
  { value: "sant_kabir_nagar",        label: "Sant Kabir Nagar",         parentValue: "uttar_pradesh" },
  { value: "shahjahanpur",            label: "Shahjahanpur",             parentValue: "uttar_pradesh" },
  { value: "shamli",                  label: "Shamli",                   parentValue: "uttar_pradesh" },
  { value: "shrawasti",               label: "Shrawasti",                parentValue: "uttar_pradesh" },
  { value: "siddharthnagar",          label: "Siddharthnagar",           parentValue: "uttar_pradesh" },
  { value: "sitapur",                 label: "Sitapur",                  parentValue: "uttar_pradesh" },
  { value: "sonbhadra",               label: "Sonbhadra",                parentValue: "uttar_pradesh" },
  { value: "sultanpur",               label: "Sultanpur",                parentValue: "uttar_pradesh" },
  { value: "unnao",                   label: "Unnao",                    parentValue: "uttar_pradesh" },
  { value: "varanasi",                label: "Varanasi",                 parentValue: "uttar_pradesh" },

  // ── Uttarakhand (13) ──
  { value: "almora",                  label: "Almora",                   parentValue: "uttarakhand" },
  { value: "bageshwar",               label: "Bageshwar",                parentValue: "uttarakhand" },
  { value: "chamoli",                 label: "Chamoli",                  parentValue: "uttarakhand" },
  { value: "champawat",               label: "Champawat",                parentValue: "uttarakhand" },
  { value: "dehradun",                label: "Dehradun",                 parentValue: "uttarakhand" },
  { value: "haridwar",                label: "Haridwar",                 parentValue: "uttarakhand" },
  { value: "nainital",                label: "Nainital",                 parentValue: "uttarakhand" },
  { value: "pauri_garhwal",           label: "Pauri Garhwal",            parentValue: "uttarakhand" },
  { value: "pithoragarh",             label: "Pithoragarh",              parentValue: "uttarakhand" },
  { value: "rudraprayag",             label: "Rudraprayag",              parentValue: "uttarakhand" },
  { value: "tehri_garhwal",           label: "Tehri Garhwal",            parentValue: "uttarakhand" },
  { value: "udham_singh_nagar",       label: "Udham Singh Nagar",        parentValue: "uttarakhand" },
  { value: "uttarkashi",              label: "Uttarkashi",               parentValue: "uttarakhand" },

  // ── West Bengal (23) ──
  { value: "alipurduar",              label: "Alipurduar",               parentValue: "west_bengal" },
  { value: "bankura",                 label: "Bankura",                  parentValue: "west_bengal" },
  { value: "birbhum",                 label: "Birbhum",                  parentValue: "west_bengal" },
  { value: "cooch_behar",             label: "Cooch Behar",              parentValue: "west_bengal" },
  { value: "dakshin_dinajpur",        label: "Dakshin Dinajpur",         parentValue: "west_bengal" },
  { value: "darjeeling",              label: "Darjeeling",               parentValue: "west_bengal" },
  { value: "hooghly",                 label: "Hooghly",                  parentValue: "west_bengal" },
  { value: "howrah",                  label: "Howrah",                   parentValue: "west_bengal" },
  { value: "jalpaiguri",              label: "Jalpaiguri",               parentValue: "west_bengal" },
  { value: "jhargram",                label: "Jhargram",                 parentValue: "west_bengal" },
  { value: "kalimpong",               label: "Kalimpong",                parentValue: "west_bengal" },
  { value: "kolkata",                 label: "Kolkata",                  parentValue: "west_bengal" },
  { value: "malda",                   label: "Malda",                    parentValue: "west_bengal" },
  { value: "murshidabad",             label: "Murshidabad",              parentValue: "west_bengal" },
  { value: "nadia",                   label: "Nadia",                    parentValue: "west_bengal" },
  { value: "north_24_parganas",       label: "North 24 Parganas",        parentValue: "west_bengal" },
  { value: "paschim_bardhaman",       label: "Paschim Bardhaman",        parentValue: "west_bengal" },
  { value: "paschim_medinipur",       label: "Paschim Medinipur",        parentValue: "west_bengal" },
  { value: "purba_bardhaman",         label: "Purba Bardhaman",          parentValue: "west_bengal" },
  { value: "purba_medinipur",         label: "Purba Medinipur",          parentValue: "west_bengal" },
  { value: "purulia",                 label: "Purulia",                  parentValue: "west_bengal" },
  { value: "south_24_parganas",       label: "South 24 Parganas",        parentValue: "west_bengal" },
  { value: "uttar_dinajpur",          label: "Uttar Dinajpur",           parentValue: "west_bengal" },
];
